feat: blue/green 배포를 위한 CD 파이프라인 스크립트 수정

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -58,22 +58,101 @@ jobs:
       - name: Build and Push Docker image
         run: docker buildx build --push --platform linux/amd64 -t kimsongmok/splanet:${{ env.IMAGE_TAG }} .
 
-      - name: Deploy to EC2
+      - name: Determine Current Version
+        id: current_version
         uses: appleboy/ssh-action@v0.1.6
         with:
           host: ${{ secrets.EC2_HOST }}
           username: ubuntu
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
+            if sudo docker ps --filter "name=splanet_blue" --format "{{.Names}}" | grep -q "splanet_blue"; then
+              echo "::set-output name=version::blue"
+            elif sudo docker ps --filter "name=splanet_green" --format "{{.Names}}" | grep -q "splanet_green"; then
+              echo "::set-output name=version::green"
+            else
+              echo "::set-output name=version::none"
+            fi
+
+      - name: Deploy New Version to EC2
+        uses: appleboy/ssh-action@v0.1.6
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ubuntu
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            if [ "${steps.current_version.outputs.version}" == "blue" ]; then
+              NEW_VERSION="green"
+              NEW_PORT=8081
+            else
+              NEW_VERSION="blue"
+              NEW_PORT=8080
+            fi
             sudo docker pull kimsongmok/splanet:${{ env.IMAGE_TAG }}
-            sudo docker stop splanet || true
-            sudo docker rm splanet || true
             sudo docker network inspect splanet >/dev/null 2>&1 || sudo docker network create splanet
-            sudo docker run -d --name splanet_blue \
+            sudo docker run -d --name splanet_${NEW_VERSION} \
               --network splanet \
               --env-file /home/ubuntu/env.properties \
-              -p 8080:8080 --restart unless-stopped kimsongmok/splanet:${{ env.IMAGE_TAG }}
+              -p ${NEW_PORT}:8080 --restart unless-stopped kimsongmok/splanet:${{ env.IMAGE_TAG }}
+
+      - name: Wait for Spring Boot Application to Start
+        uses: appleboy/ssh-action@v0.1.6
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ubuntu
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            if [ "${steps.current_version.outputs.version}" == "blue" ]; then
+              NEW_PORT=8081
+            else
+              NEW_PORT=8080
+            fi
             
+            echo "Waiting for the application to be healthy on http://api.splanet.co.kr:${NEW_PORT}/actuator/health..."
+            for i in {1..30}; do
+              if curl -s http://api.splanet.co.kr:${NEW_PORT}/actuator/health | grep '"status":"UP"' > /dev/null; then
+                echo "Application is healthy and ready to receive traffic."
+                break
+              fi
+              echo "Waiting for application to start... (Attempt $i)"
+              sleep 5
+            done
+            
+            # If the application is not healthy after 40 attempts (200 seconds), fail the deployment
+            if [ "$i" -eq 30 ]; then
+              echo "Application did not start successfully within the expected time."
+              sudo docker logs splanet_${NEW_VERSION}
+              exit 1
+            fi
+
+      - name: Update Load Balancer Target Group
+        uses: appleboy/ssh-action@v0.1.6
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ubuntu
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            if [ "${{ steps.current_version.outputs.version }}" == "blue" ]; then
+              TARGET_GROUP_ARN="arn:aws:elasticloadbalancing:ap-northeast-2:${{ secrets.AWS_ACCOUNT_ID }}:targetgroup/splanet-8081/${{ secrets.ARN_ID_8081 }}"
+            else
+              TARGET_GROUP_ARN="arn:aws:elasticloadbalancing:ap-northeast-2:${{ secrets.AWS_ACCOUNT_ID }}:targetgroup/splanet/${{ secrets.ARN_ID_8080 }}"
+            fi
+            aws elbv2 modify-listener --listener-arn arn:aws:elasticloadbalancing:ap-northeast-2:${{ secrets.AWS_ACCOUNT_ID }}:listener/app/splanet/${{ secrets.ARN_ID_443 }} \
+              --default-actions Type=forward,TargetGroupArn=$TARGET_GROUP_ARN
+
+      - name: Remove Old Version
+        uses: appleboy/ssh-action@v0.1.6
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ubuntu
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script: |
+            if [ "${{ steps.current_version.outputs.version }}" != "none" ]; then
+              sudo docker stop splanet_${{ steps.current_version.outputs.version }}
+              sudo docker rm splanet_${{ steps.current_version.outputs.version }}
+            fi
+
+
       - name: Clean up old Docker images
         uses: appleboy/ssh-action@v0.1.6
         with:
